### ISSUE TITLE
request: Publish artifacts for public consumption

### ISSUE THREAD

**Issue by paiyar** [adobe/experience-platform-streaming-connect#10]
Background
---
Could you please publish artifacts for public consumption? There is no official plugin published to public maven repositories, nor github releases, nor [Connect Hub](https://www.confluent.io/hub/) as the usage documentation to linked to in the README would have one believe: https://github.com/adobe/experience-platform-streaming-connect/blame/96b38a21001a8c0224c33fab2fc6b5ac82191110/README.md#L38 . The artifacts seem to only be published internally: https://github.com/adobe/experience-platform-streaming-connect/blob/96b38a21001a8c0224c33fab2fc6b5ac82191110/build.gradle#L63

As of current users are relegated to clone and use a non-hermetic build system (gradle) to produce local copies of the connect jar.

Could you please make an official release of the plugin and accompanying docker images referred to in the documentation?

**Comment by nipunnair** [comment]
@paiyar published the latest release here : https://github.com/adobe/experience-platform-streaming-connect/releases/tag/v0.0.3

Thanks for pointing this out, will also be publishing the connector to Confluent Hub soon
