### ISSUE TITLE
There is a bug generating an access token when the aep.connection.auth.token.type is jwt_token

### ISSUE THREAD

**Issue by vinodrajmh** [adobe/experience-platform-streaming-connect#14]
### Subject of the issue
There is a bug generating an access token when the aep.connection.auth.token.type is jwt_token

### Your environment
* version of docker

### Steps to reproduce
Set the "aep.connection.auth.token.type": "jwt_token" 
    "aep.connection.auth.token.type": "jwt_token",
    "aep.connection.auth.imsOrg" : "<ims org>",
    "aep.connection.auth.accountKey": "<technical account id>",
    "aep.connection.auth.filePath" :"<private key path >"
    "AUTH_ENDPOINT" : "auth_end_point"

technicalAccountKey account is used 

 "aep.connection.auth.client.id": "<client id>",

### Expected behaviour
Should generate access token

### Actual behaviour
It will fail to generate access token as technicalAccountKey  is used to generate access token client secret.

Current source code doesn't have variable to accept client code ,needs a fix in the code to add this extra variable and pass the relevant client secret variable while generating the access token.

**Comment by nipunnair** [comment]
fixed

**Comment by nipunnair** [comment]
@vinodrajmh this bug has been addressed, can u please verify with the latest ?

**Comment by vinodrajmh** [comment]
@nipunnair  Jwt Token Athentication works fine now.
