### ISSUE TITLE
Requesting for an Update in the readme file about authentication types.

### ISSUE THREAD

**Issue by vinodrajmh** [adobe/experience-platform-streaming-connect#15]
### Subject of the issue
Requesting to update the readme file on the different authentication types as the current document has details only an access token type.
### Your environment
* version of docker

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Need an update on the readme(developer guide) documentation on authentication using jwt token type.
### Actual behavior
Currently, we have steps only on access token type.

**Comment by nipunnair** [comment]
@vinodrajmh can u comment on whether the Doc update mentioned in the developer guide is clear : https://github.com/adobe/experience-platform-streaming-connect/blob/master/DEVELOPER_GUIDE.md#authentication-enabled

**Comment by vinodrajmh** [comment]
@nipunnair The document is updated with really useful info now. Thanks for the quick help.
