### ISSUE TITLE
Needs an enhancement in the source code to handle the raw json ingestion via kafka connect 

### ISSUE THREAD

**Issue by vinodrajmh** [adobe/experience-platform-streaming-connect#16]
### Subject of the issue
Requesting feature enhancement of Kafka connector for raw streaming ingestion.

### Your environment
* version of docker

### Steps to reproduce
Try sending raw JSON(NON-XDM) message from Kafka topic into AEP endpoint through Kafka connect instance. 

### Expected behaviour
Data should ingest into the AEP dataset

### Actual behaviour
AS we do not have the facility to stream the raw data via Kafka connector, since we don't have an option to pass the header info (x-adobe-flow-id and x-adobe-dataset-id). data ingestion into the AEP dataset  will not happen

**Comment by nipunnair** [comment]
@vinodrajmh this has been addressed. Please validate and update

**Comment by vinodrajmh** [comment]
@nipunnair Thanks for the enhancement. It works fo ingesting raw json data now.
