### ISSUE TITLE
Update the build process to override the gradle properties version

### ISSUE THREAD

**Issue by nipunnair** [adobe/experience-platform-streaming-connect#29]
### Subject of the issue
The build by default always takes in the last known version and updates it. Sometimes we want to overrride this. 

### Your environment
* version of docker

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us the actual behaviour

**Comment by vivetiwa** [comment]
Update to build version is done as part of PR done for release connector to confluent hub - https://github.com/adobe/experience-platform-streaming-connect/pull/33
