### ISSUE TITLE
Proxy support not supporting all Adobe URLs

### ISSUE THREAD

**Issue by swapdesai** [adobe/experience-platform-streaming-connect#30]
### Subject of the issue
Proxy support not supporting all Adobe URLs

### Your environment
KAFKA Version: 2.8.0
AEP Connector tag release: v0.0.8 

### Steps to reproduce
Within a corporate environment where all HTTP(S) connections should go over a HTTP proxy host, the AEP connector does connect to only certain Adobe urls.

### Expected behaviour
The connector must be able to establish a connection and communicate with all the Adobe urls.

### Actual behaviour
AEP Connector does not connect to all Adobe urls within a proxy environment.

**Comment by vivetiwa** [comment]
Fix done as part of PR https://github.com/adobe/experience-platform-streaming-connect/pull/31
