### ISSUE TITLE
Add support for ingesting AVRO format into Kafka Sink Connector

### ISSUE THREAD

**Issue by coolaries30** [adobe/experience-platform-streaming-connect#49]
### Subject of the issue
Please add support for ingesting AVRO File Format into AEP.

### Your environment
* version of docker

### Steps to reproduce
Tell us how to reproduce this issue.

### Expected behaviour
AEP is currently unable to ingest AVRO data format for Streaming Kafka Sink Connector.

### Actual behaviour
Kafka Sink Connector in AEP should be able to ingest events in AVRO format.

**Comment by OneCricketeer** [comment]
I assume you mean Confluent encoded records, from their Schema Registry rather than raw Avro encoding? And not "files" as these are binary records?

**Comment by coolaries30** [comment]
Hi Jordan,

I mean raw streaming event records in AVRO Format which have an AVRO Schema
defined in the Schema Registry. AEP currently only accepts JSON records but
we would like to have support for AVRO format as well.

Thanks,
Sudhir

**Comment by OneCricketeer** [comment]
My question is more about, have you tried this already? What errors are you seeing? 

```
value.converter=io.confluent...AvroConverter
value.converter.schema.registry.url=...
```

Or this one if not using any registry?https://github.com/farmdawgnation/registryless-avro-converter

More specifically, AEP exposes a well documented API, separately from this connector. It needs JSON payloads, but this Connector simply deserializes Kafka events defined by the Connect API `SinkRecord` type and passes them through, and those could be any format that has an associated Converter.

**Comment by OneCricketeer** [comment]
Non-JSON Converter support should be possible with #54

**Comment by OneCricketeer** [comment]
The above PR has been merged and docs are added to the README
