### ISSUE TITLE
Implement new OAuth token authentication flow

### ISSUE THREAD

**Issue by vivetiwa** [adobe/experience-platform-streaming-connect#50]
### Subject of the issue
New OAuth client credential token flow implementation needs to be done as JWT token will is deprecated.

**Comment by AchimKre** [comment]
Hi, Is there still a way to set up a JWT authentication at https://developer.adobe.com/console? I can only configure the OAuth Server-to-Server credentials, but no JWT authentication anymore. Since JWT authentication is deprecated, does that means the Kafka Connector is deprecated as well?

**Comment by vivetiwa** [comment]
Implemented as part of PR - https://github.com/adobe/experience-platform-streaming-connect/pull/63
