### ISSUE TITLE
Using an Existing Topic in a separate Kafka Cluster to send Data to AEP

### ISSUE THREAD

**Issue by del57361** [adobe/experience-platform-streaming-connect#7]
### Subject of the issue
Using an Existing Topic in a separate Kafka Cluster to send Data to AEP

### Expected behaviour
Instead of creating a topic through the Kafka Connector can we use the Adobe Sink Connector to send data from an existing topic? Are there any constraints or extra configurations for doing so?

**Comment by nipunnair** [comment]
Yes, though the documentation refers to creating a new topic, we can configure the kafka connect worker to point to existing topic in the broker. There are no constraints related to this - the setup is similar to any generic kafka connect setup
